language: python
sudo: false
env:
  matrix:
    - LUA="lua=5.2"
branches:
  only:
    - master
    - develop
before_install:
  - echo $TRAVIS_EVENT_TYPE
  - pip install hererocks
  - hererocks ~/build/lua_install -r^ --$LUA
  - export PATH=$PATH:~/build/lua_install/bin
install:
  - luarocks install luacheck
script:
  - "if [[ $TRAVIS_EVENT_TYPE != 'cron' ]]; then luacheck .; fi"
before_deploy:
  - git config --local user.name "$github_user_name"
  - git config --local user.email "$github_user_email"
  - DATE_FORMATTED=$(date +'%Y-%m-%d')
  - export DATE_FORMATTED
  - COMMIT_SHA=$(git log --format=%h -1)
  - export COMMIT_SHA
  - TRAVIS_TAG="nightly/"$DATE_FORMATTED-$COMMIT_SHA
  - export TRAVIS_TAG
  - git tag "$TRAVIS_TAG"
  - RELEASE_NAME='Nightly release - '"$DATE_FORMATTED"' - '"$COMMIT_SHA"
  - export RELEASE_NAME
  - ./.travis/release_builder.sh
deploy:
  on:
    condition: $TRAVIS_EVENT_TYPE = cron
    repo: plague006/RedMew
    branch: develop
  provider: releases
  api_key:
    secure: 3LnvdRAePdWDqVkHW7tn9rPQ9rWbBRJuUR/ImK0z+cHEkN/VYvo65S7bc4Ij1zIkQ5Qq4ljSxAy7zNafIsAqeTES9xDiveGxaLt+lmNI//eW024aKEcK1IkGLiGvff64J3LMw+cXwLGXMEKtx7q2Qd3QSYpjXxqOWA1OyfuHw/jyatpNHx2PKbA6e6s0ll3tYRhsGRmaCAGoPdBKwfVF5YIRauZUUp7pYpz4RFp+QTd/opTJhr0EOciwZxmIGmgXU2roKb5d9mt5B7IZGtOXCZNtFCZTJTAvgL4pjuFnpF4Cs0XZ0c/uihLT2B1bLqjjvbks2FHaLCgu6FdApwb28SfovbO98qxkuuaIYYJOrCiZ8zwtnhutkYr/Zs5Vdc5CEbm7YUjEIBKharlR8Pc5baRAQH4SOG13QYLqbKonQKUDHUUQWLs2ZugiT+m9QH7RbvSB/ji/cB+ksZiOKMRyfXWTJgdj48LicE9oKIpWcIk3gjzs1PONHM7Ie8c4UdfLdxoAQV7Of8OmCu41OtXAcErDL60TJleXh/bHFNyoDM/fukekbH6WewEteKkBUO0ylMZJVeTtIAwkp0jSuba8aUtIZXau947mz0j4f9Yf2WzasNuINHbWt7FNU6RThBgNun6zFXRWhrJ6JudM/R6UhDondPZmOUo+l1esoIue5FY=
  file:
    - RedMew.zip
    #- Diggy.zip
    #- Crashsite.zip
  skip_cleanup: true
  #prerelease: true
  draft: true #after the testing phase, this will be deleted and we will issue prereleases
  name: "$RELEASE_NAME"
